server:
  port: 8082

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

eureka:
  instance:
    prefer-ip-address: true
    hostname: file-processor-service
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://discovery-server:8761/eureka/

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
